"""Build knowledge/general_facts.json: a small curated pack of general-knowledge facts for offline Ask.

Capitals come from Wikidata (CC0) via its public SPARQL endpoint: every sovereign state (instance of Q6256,
not dissolved) with its capital (P36). The seven SI base units are typed in from the SI Brochure (BIPM).
Nothing is generated by a model. Run once with a network connection: python -m tools.build_general_facts
"""
from __future__ import annotations

import json
import pathlib
import urllib.parse
import urllib.request

OUT = pathlib.Path(__file__).resolve().parent.parent / "knowledge" / "general_facts.json"
QUERY = ('SELECT ?c ?cLabel ?k ?kLabel WHERE { ?c wdt:P31 wd:Q6256; wdt:P36 ?k. '
         'FILTER NOT EXISTS { ?c wdt:P576 [] } SERVICE wikibase:label { bd:serviceParam wikibase:language "en". } }')
SI = [("metre", "m", "length"), ("kilogram", "kg", "mass"), ("second", "s", "time"),
      ("ampere", "A", "electric current"), ("kelvin", "K", "thermodynamic temperature"),
      ("mole", "mol", "amount of substance"), ("candela", "cd", "luminous intensity")]
SI_SOURCE = "https://www.bipm.org/en/publications/si-brochure"


def _unlabelled(s: str) -> bool:
    return s.startswith("Q") and s[1:].isdigit()


def capitals() -> list[dict]:
    req = urllib.request.Request("https://query.wikidata.org/sparql?format=json&query=" + urllib.parse.quote(QUERY),
                                 headers={"User-Agent": "machine-memory-edge/0.1 (local build)"})
    rows = json.load(urllib.request.urlopen(req, timeout=60))["results"]["bindings"]
    by: dict[str, dict] = {}
    for r in rows:
        qid, name, cap = r["c"]["value"].rsplit("/", 1)[1], r["cLabel"]["value"], r["kLabel"]["value"]
        if _unlabelled(name) or _unlabelled(cap):
            continue                                  # an entity with no English label
        by.setdefault(qid, {"country": name, "capitals": []})["capitals"].append(cap)
    facts = []
    for qid, c in sorted(by.items(), key=lambda kv: kv[1]["country"]):
        caps = sorted(set(c["capitals"]))
        text = (f"The capital of {c['country']} is {caps[0]}." if len(caps) == 1 else
                f"The capitals of {c['country']} are {', '.join(caps[:-1])} and {caps[-1]}.")
        facts.append({"id": f"capital:{qid}", "title": f"Capital of {c['country']}", "text": text,
                      "sources": [f"https://www.wikidata.org/wiki/{qid}"]})
    return facts


def si_units() -> list[dict]:
    return [{"id": f"si:{n}", "title": f"SI base unit of {q}",
             "text": f"The SI base unit of {q} is the {n} (symbol {s}).", "sources": [SI_SOURCE]}
            for n, s, q in SI]


def main() -> None:
    facts = capitals() + si_units()
    OUT.write_text(json.dumps({"licence": "Wikidata CC0; SI Brochure (BIPM) for the base units",
                               "facts": facts}, ensure_ascii=False, indent=1), encoding="utf-8")
    print(f"wrote {len(facts)} facts to {OUT}")


if __name__ == "__main__":
    main()
